export const CATEGORY_MAPPINGS: any = {
  SOCIAL_IMPACT: "Social Impact",
  NON_PROFIT: "NonProfit",
  CLIMATE: "Climate",
  PUBLIC_GOOD: "Public Good",
  DE_SCI: "DeSci",
  OPEN_SOURCE: "Open Source",
  COMMUNITY: "Community",
  EDUCATION: "Education",
  _deprecated: {
    "social-impact": "SOCIAL_IMPACT",
    "non-profit": "NON_PROFIT",
    climate: "CLIMATE",
    "public-good": "PUBLIC_GOOD",
    "de-sci": "DE_SCI",
    "open-source": "OPEN_SOURCE",
    community: "COMMUNITY",
    education: "EDUCATION",
  },
};
